### ISSUE TITLE
docker image registry not working🐛 

### ISSUE THREAD

**Issue by bnwlf** [icgc-argo/charts#132]
The new (commit c39092f4e916f2290d6adaab301e793af51efc39) ghcr registry is not working for me. The images can't be found pulled. Is it a closed registry?
Cheers,
Ben

**Comment by andricDu** [comment]
Hi @bnwlf 
Its a public registry. Our move to ghcr is not a mirror of docker hub, so for historical images you will still need to pull from dockerhub. For that you can override the repository value for the helm chart.

The current available version we have are: https://github.com/orgs/icgc-argo/packages/container/workflow-management/versions

**Comment by bnwlf** [comment]
Ah! I tried to load the version with the latest tag as given in the helm chart. By replacing it by edge it worked. It would be nice to have the latest versions also in the new registry.
