### ISSUE TITLE
Update workflow-traffic charts for podSecurity

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/charts#65]
Refer [argo-gateway infra](https://github.com/icgc-argo/charts/blob/master/argo-gateway) for reference:
https://github.com/icgc-argo/charts/blob/master/argo-gateway/templates/deployment.yaml#L22-L25

and

https://github.com/icgc-argo/charts/blob/master/argo-gateway/values.yaml#L19-L22

**Comment by akachru-github** [comment]
This is not deployed and there is no docker yet.
